### ISSUE TITLE
Clarity Phone Survey: Road Map

### ISSUE THREAD

**Issue by nickeubank** [Duke-Translational-Bioinformatics/covid19#5]
@danclarity If I'm not mistaken, we're:

- [ ] Test timing (Clarity)
- [ ] Edit questions if needed (Duke folks)
- [ ] Finalize contract (status?)
- [ ] Get this in the field!

**Comment by danclarity** [comment]
Sounds correct. We've heard back from the call houses and looks like we're just under 5 minutes which is great news. We're calculating out some costs and call options and will have that around shortly. I'd definitely say if there's any more question editing folks should finalize that asap so we can move in to the field as soon as the other points here are crossed off.

**Comment by erichhuang** [comment]
Thanks for the update @danclarity.
